sonar.projectKey=bobcowher_beekeeper
sonar.organization=robertcowher

sonar.sources=.
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=\
  venv/**,\
  projects/**,\
  .github/**,\
  **/__pycache__/**,\
  **/site-packages/**

sonar.coverage.exclusions=\
  tests/**,\
  venv/**,\
  projects/**
